clientes:
    resource: "@ClientesBundle/Controller/"
    type:     annotation
    prefix:   /clientes/

restaurante:
    resource: "@RestauranteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
